name: morning
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ wx8269d557e2e70324 }}
      APP_SECRET: ${{f62b9c6e83890a7a2cca5b172f97e01c }}
      TEMPLATE_ID: ${{ 	Tn8MZtz1Iks-03bnLJJilQE34GdwTsnss0xl-c8dK2w	}}
      USER_ID: ${{ oeXG45nzND2f80WUrE4FAdkEvxrk }}
      START_DATE: ${{ 08-24 }}
      BIRTHDAY: ${{ 10-25 }}
      CITY: ${{ secrets.CITY }}
      USERS_ID: ${{ secrets.USERS_ID }}
